/****** 表名需要从库一级开始指定，use 切换数据库并不好用，如果不指定库，表会默认建立到 master 库下 ******/
USE [master]
GO

CREATE DATABASE [SiteDownLoader]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SiteDownLoader', FILENAME = N'mdfSavePath' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SiteDownLoader_log', FILENAME = N'ldfSavePath' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SiteDownLoader] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SiteDownLoader].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SiteDownLoader] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SiteDownLoader] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SiteDownLoader] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SiteDownLoader] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SiteDownLoader] SET ARITHABORT OFF 
GO

ALTER DATABASE [SiteDownLoader] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SiteDownLoader] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SiteDownLoader] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SiteDownLoader] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SiteDownLoader] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SiteDownLoader] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SiteDownLoader] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SiteDownLoader] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SiteDownLoader] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SiteDownLoader] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SiteDownLoader] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SiteDownLoader] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SiteDownLoader] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SiteDownLoader] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SiteDownLoader] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SiteDownLoader] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SiteDownLoader] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SiteDownLoader] SET RECOVERY FULL 
GO

ALTER DATABASE [SiteDownLoader] SET  MULTI_USER 
GO

ALTER DATABASE [SiteDownLoader] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SiteDownLoader] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SiteDownLoader] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SiteDownLoader] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SiteDownLoader] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SiteDownLoader] SET QUERY_STORE = OFF
GO

USE [SiteDownLoader]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SiteDownLoader] SET  READ_WRITE 
GO

USE [SiteDownLoader]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SiteDownLoader].[dbo].[t_sites](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](255) NULL,
	[url] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_t_sites] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [SiteDownLoader]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SiteDownLoader].[dbo].[t_urls](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[site_id] [int] NOT NULL,
	[url] [nvarchar](max) NOT NULL,
	[downloaded] [bit] NULL,
	[download_time] [datetime] NULL,
 CONSTRAINT [PK_t_urls] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [SiteDownLoader].[dbo].[t_urls] ADD  CONSTRAINT [DF_t_urls_downloaded]  DEFAULT ((0)) FOR [downloaded]
GO

USE [SiteDownLoader]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [SiteDownLoader].[dbo].[t_paths](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[url_id] [int] NOT NULL,
	[path] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_t_paths] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

